// Code generated by pioasm; DO NOT EDIT.

// +build rp2040

package main

// ws2812

const ws2812_wrap_target = 0
const ws2812_wrap = 3

const ws2812_T1 = 2
const ws2812_T2 = 5
const ws2812_T3 = 3

var ws2812_program_instructions = []uint16{
	//     .wrap_target
	0x6221, //  0: out    x, 1            side 0 [2] 
	0x1123, //  1: jmp    !x, 3           side 1 [1] 
	0x1400, //  2: jmp    0               side 1 [4] 
	0xa442, //  3: nop                    side 0 [4] 
	//     .wrap
}



// ws2812_parallel

const ws2812_parallel_wrap_target = 0
const ws2812_parallel_wrap = 3

const ws2812_parallel_T1 = 2
const ws2812_parallel_T2 = 5
const ws2812_parallel_T3 = 3

var ws2812_parallel_program_instructions = []uint16{
	//     .wrap_target
	0x6020, //  0: out    x, 32                      
	0xa10b, //  1: mov    pins, !null            [1] 
	0xa401, //  2: mov    pins, x                [4] 
	0xa103, //  3: mov    pins, null             [1] 
	//     .wrap
}



